spring.application.name=SpringCloudGateWay

# 마이크로 서버의 포트 번호가 8080, 8081, 8082 이므로 8000으로 할당함
server.port=8000

spring.cloud.gateway.mvc.routes[0].id=ms1
# Path 방식 라우팅 사용
spring.cloud.gateway.mvc.routes[0].predicates[0].name=Path
# /ms1/ 로 시작하는 url을 감지
spring.cloud.gateway.mvc.routes[0].predicates[0].args.pattern=/ms1/**
# 해당 url을 8080 포트로 포워딩
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8080

spring.cloud.gateway.mvc.routes[1].id=ms2
spring.cloud.gateway.mvc.routes[1].predicates[0].name=Path
spring.cloud.gateway.mvc.routes[1].predicates[0].args.pattern=/ms2/**
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8081

spring.cloud.gateway.mvc.routes[2].id=normal
spring.cloud.gateway.mvc.routes[2].predicates[0].name=Path
spring.cloud.gateway.mvc.routes[2].predicates[0].args.pattern=/normal/**
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8082