# 마이크로 서버의 포트 번호가 8080, 8081, 8082 이므로 8000으로 할당함
server:
  port: 8088

spring:
  application:
    name: SpringCloudGateWay
#  yml으로 라우팅과 지역 필터 설정하는 법
#  cloud:
#    gateway:
#      routes:
#        - id: ms1
#          uri: http://localhost:8080
#          predicates:
#            - Path=/ms1/**
#          filters:
#            - name: L1Filter
#              args:
#                pre: true
#                post: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}