spring.application.name=monitoring

server.port=8080

management.endpoints.web.exposure.include=health, prometheus, info
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=demo-app