spring.application.name=SCG_Actuator

server.port=8088

# none -> ????? ????
# read-only -> GET ??? ??
# unrestricted -> ?? HTTP ??? ??
management.endpoint.gateway.access=unrestricted
#management.endpoint.gateway.enabled=true ? ?? ???? ??
management.endpoints.web.exposure.include=gateway

spring.cloud.gateway.routes[0].id=normal
spring.cloud.gateway.routes[0].predicates[0].name=Path
spring.cloud.gateway.routes[0].predicates[0].args.patterns=/normal/**
spring.cloud.gateway.routes[0].uri=http://localhost:8082