# Config Repo = ms1-dev.properties
# CONFIG_NAME = ms1
spring.application.name=${CONFIG_NAME}
# CONFIG_ENV = dev
spring.profiles.active=${CONFIG_ENV}
# optional:configserver:http://ID:PW@IP:Port
spring.config.import=optional:configserver:${CONFIG_SERVER}

# ${}안의 변수명이 Config Repo의 변수명과 동일하면 된다.
# server.port 같이 application.properties와 Config Repo의 변수명이 같을 경우 생략 가능
TEST_VAR=${TEST_VAR}
