spring.application.name=${CONFIG_NAME}
spring.profiles.active=${CONFIG_ENV}
# optional:configserver:http://ID:PW@IP:Port
spring.config.import=optional:configserver:${CONFIG_SERVER}

TEST_VAR=${TEST_VAR}